# Generated by Django 5.2 on 2025-10-10 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_fileupload_delete_encryptedfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileupload',
            name='file',
        ),
        migrations.AddField(
            model_name='fileupload',
            name='encrypted_content',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fileupload',
            name='filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
