# Generated by Django 5.0.7 on 2025-10-10 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_remove_fileupload_file_fileupload_encrypted_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='is_malicious',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fileupload',
            name='scan_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fileupload',
            name='sha256',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
