# Generated by Django 5.2.8 on 2025-11-07 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0005_add_security_checks_and_audit_log'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='files_audit_user_id_4491a4_idx',
            old_name='files_audit_user_time_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='files_audit_action_445265_idx',
            old_name='files_audit_action_time_idx',
        ),
    ]
