# Generated by Django 5.1.3 on 2025-11-09 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0006_rename_files_audit_user_time_idx_files_audit_user_id_4491a4_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='is_encrypted',
            field=models.BooleanField(default=True),
        ),
    ]
