# Generated by Django 5.1.3 on 2025-11-09 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0007_fileupload_is_encrypted'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='encryption_key',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fileupload',
            name='recovery_key',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
